Vagrant.configure("2") do |config|
  #config.vm.communicator = "winrm"
  config.vm.box = "hps/win-2012r2-amd64-nocm"
  config.vm.provider "virtualbox" do |vb|
      vb.gui = true  # Display the VirtualBox GUI when booting the machine
  end
  
  config.vm.synced_folder "./../Enrollment","C:/Dsc_Enrollment"
  config.vm.provision "shell", inline: "wusa.exe C:/Dsc_Enrollment/WMF_5.1 .msu /quiet" #installs PSv5.1
  #config.vm.provision "shell", inline: "C:/Dsc_Enrollment/bootstrap-AzureDsc.ps1"
end
